Update user docs for running `llm server` + upgrade `gguf` to `0.11.0` (#676)
# Description

Did a pass through and made updates + fixes to the user docs for
`e2e_llama8b_mi300x.md`.

1. Update install instructions for `shark-ai`
2. Update nightly install instructions for `shortfin` and `sharktank`
3. Update paths for model artifacts to ensure they work with
`llama3.1-8b-fp16-instruct`
4. Remove steps to `write edited config`. No longer needed after #487 

Added back `sentencepiece` as a requirement for `sharktank`. Not having
it caused `export_paged_llm_v1` to break when installing nightly:

```text
ModuleNotFoundError: No module named 'sentencepiece'
```

This was obfuscated when building from source, because `shortfin`
includes `sentencepiece` in `requirements-tests.txt`.