Add a few mistral/mixtral datasets to hf_datasets.py. (#16)
## `mistral_7b_q8_0_gguf`

* Model from https://huggingface.co/TheBloke/Mistral-7B-v0.1-GGUF
* Tokenizer from https://huggingface.co/TheBloke/Mistral-7B-v0.1-GPTQ

This works on my machine:

```
python -m sharktank.examples.paged_llm_v1 --hf-dataset=mistral_7b_q8_0_gguf "1, 2, 3, 4"
:: Prompting:
    b'1, 2, 3, 4'
:: Prompt tokens: tensor([[    1, 28705, 28740, 28725, 28705, 28750, 28725, 28705, 28770, 28725,
         28705, 28781,     0,     0,     0,     0]])
:: Invoke prefill:
:: Prefill results:
[[28725]]
[',']
:: Result tokens: [[28725, 28705]]
  0(2, 13): ,
:: Result tokens: [[28725, 28705, 28782]]
  0(3, 14): , 5
:: Result tokens: [[28725, 28705, 28782, 28725]]
  0(4, 15): , 5,
:: Result tokens: [[28725, 28705, 28782, 28725, 28705]]
  0(5, 16): , 5, 
:: Result tokens: [[28725, 28705, 28782, 28725, 28705, 28784]]
  0(6, 17): , 5, 6
```

## `mistral_7b_q4_k_m_gguf`

* Model from https://huggingface.co/TheBloke/Mistral-7B-v0.1-GGUF
* Tokenizer from https://huggingface.co/TheBloke/Mistral-7B-v0.1-GPTQ

This is missing support for `Q6_K` and possibly also `Q5_K`:

```
python -m sharktank.examples.paged_llm_v1 --hf-dataset=mistral_7b_q4_k_m_gguf "1, 2, 3, 4"
mistral-7b-v0.1.Q4_K_M.gguf: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.37G/4.37G [00:38<00:00, 115MB/s]
:: Prompting:
    b'1, 2, 3, 4'
:: Prompt tokens: tensor([[    1, 28705, 28740, 28725, 28705, 28750, 28725, 28705, 28770, 28725,
         28705, 28781,     0,     0,     0,     0]])
:: Invoke prefill:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\dev\projects\sharktank\sharktank\sharktank\examples\paged_llm_v1.py", line 255, in <module>
    main()
  File "D:\dev\projects\sharktank\sharktank\sharktank\examples\paged_llm_v1.py", line 245, in main
    batch.prefill()
  File "D:\dev\projects\sharktank\sharktank\sharktank\examples\paged_llm_v1.py", line 147, in prefill
    logits = model.prefill(
             ^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\sharktank\sharktank\models\llama\llama.py", line 172, in prefill
    h = block(
  File "D:\dev\projects\sharktank\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\sharktank\sharktank\models\llama\llama.py", line 324, in forward
    xv = self.attn_v(x)
         ^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\sharktank\sharktank\layers\linear.py", line 35, in forward
    return self.theta.ops.matmul(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\sharktank\sharktank\types\theta.py", line 362, in matmul
    delegated = self._matmul(lhs, rhs, transpose_rhs=transpose_rhs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\sharktank\sharktank\ops\custom_inference_ops.py", line 63, in _matmul
    return handler(lhs, rhs)
           ^^^^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\sharktank\sharktank\ops\custom_inference_ops.py", line 80, in _mmt_block_scaled_q4
    rhs_unpacked = rhs.unpack()
                   ^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\sharktank\sharktank\types\gguf_interop\layouts.py", line 241, in unpack
    raise NotImplementedError
NotImplementedError
```

## `mixtral_8x7b_q8_0_gguf`

* Model from https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF
* Tokenizer from https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GPTQ

This needs some work:

```
python -m sharktank.examples.paged_llm_v1 --hf-dataset=mixtral_8x7b_q8_0_gguf "1, 2, 3, 4"
mixtral-8x7b-v0.1.Q8_0.gguf: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49.6G/49.6G [13:25<00:00, 61.6MB/s]
tokenizer.model: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 493k/493k [00:00<00:00, 34.0MB/s]
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 967/967 [00:00<?, ?B/s]
Traceback (most recent call last):
  File "D:\dev\projects\sharktank\sharktank\sharktank\types\theta.py", line 136, in tensor
    t = current_ts[str(last)]
        ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\dev\projects\sharktank\sharktank\sharktank\examples\paged_llm_v1.py", line 255, in <module>
    main()
  File "D:\dev\projects\sharktank\sharktank\sharktank\examples\paged_llm_v1.py", line 236, in main
    model = PagedLlamaModelV1(dataset.root_theta, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\sharktank\sharktank\models\llama\llama.py", line 136, in __init__
    [
  File "D:\dev\projects\sharktank\sharktank\sharktank\models\llama\llama.py", line 137, in <listcomp>
    PagedLlamaAttentionBlock(
  File "D:\dev\projects\sharktank\sharktank\sharktank\models\llama\llama.py", line 290, in __init__
    self.add_module("ffn_gate", LinearLayer(theta("ffn_gate")))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\sharktank\sharktank\layers\linear.py", line 31, in __init__
    self.weight = self.theta_tensor(weight_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\sharktank\sharktank\layers\base.py", line 53, in theta_tensor
    return self.theta.tensor(name)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\projects\sharktank\sharktank\sharktank\types\theta.py", line 138, in tensor
    raise KeyError(
KeyError: "Unknown parameter ('weight',) (in Theta object containing dict_keys(['0', '1', '2', '3', '4', '5', '6', '7']))"
```