Add test that exports to MLIR a small sharded Llama model (#220)
Add test that exports to MLIR a small sharded Llama model

The decode step requires exporting in non-strict torch mode due to
https://github.com/pytorch/pytorch/issues/135061

This export required to extend the registration functionality of our custom
tensor types by provinding `flatten_with_keys_fn`. This is also required
to bump the PyTorch version to >=2.4 for other export tests.

The export to MLIR fails with
TypeError: Unsupported torch type conversion for
!torch.vtensor<[3,1,7],complex<f32>>
Needs further debugging.
Detailed error
[here](https://github.com/user-attachments/files/17163454/sharded-llama-export-to-mlir-failure.txt).